app/blog/urls.py
from django.urls import path
from app.blog import views

app_name = 'blog'

urlpatterns = [
	path('home/', views.home, name='home'),
	path('tutorials/', views.all_posts, name="all_posts"),
	path('tutorials/<slug:slug>/', views.detail, name='detail'),
	path('about/', views.about, name="about"),
	path('contact/',  views.contact, name="contact_me"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('app.blog.urls', namespace='blog')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

app/blog/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField

class Category(models.Model):
	name = models.CharField(max_length=100, verbose_name='category')

	def __str__(self):
		return self.name


class Post(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	category = models.ForeignKey(Category, related_name='post', on_delete=models.CASCADE)
	title = models.CharField(max_length=255)
	description = models.CharField(max_length=500)
	content = RichTextUploadingField()
	publish = models.DateTimeField(auto_now_add=True)
	created = models.DateField(auto_now_add=True)

	class Meta:
		ordering = ['-publish', '-created']

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:detail', kwargs={'slug':  self.slug})

	@property
	def slug(self):
		return slugify(self.title)

class SubscribeUsers(models.Model):
	email = models.EmailField(unique=True, max_length=100)
	created = models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return self.email

	
	

app/blog/forms.py
from django import forms
from app.blog.models import SubscribeUsers


class SubscribeForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['email'].widget.attrs.update({'class': 'input email', 'placeholder': 'Enter your email...'})

	class Meta:
		model = SubscribeUsers
		fields = ['email']

app/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.contrib import messages
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from app.blog.models import Post, Category, SubscribeUsers
from app.blog.forms import SubscribeForm


def home(request):
	return render(request, 'pages/index.html', {})


def all_posts(request):
	
	categories = Category.objects.all()
	q = request.GET.get('q') if request.GET.get('q') !=None else ''
	posts = Post.objects.filter(Q(category__name__icontains=q) |
								Q(title__icontains=q) |
								Q(description__icontains=q))
	context = {
		'posts': posts,
		'categories': categories,
	}
	return render(request, 'pages/all_posts.html', context)


def detail(request, slug):
	post = list(filter(lambda post: post.slug==slug, Post.objects.all()))[0]
	if request.method == 'POST':
		form = SubscribeForm(request.POST)
		if form.is_valid():
			email = form.cleaned_data['email']
			subscribe_user = SubscribeUsers.objects.filter(email=email).first()
			if subscribe_user:
				messages.error(request, f"{email} email address is already subscriber.")
				return redirect('blog:detail', post.slug)
			try:
				validate_email(email)
			except ValidationError as e:
				messages.error(request, e.messages[0])
				return redirect('blog:detail', post.slug)
			subsciber = SubscribeUsers()
			subsciber.email = email
			subsciber.save()
			messages.success(request, f'{email} email was successfully subscribed to our newsletter!')
			return redirect('blog:detail', post.slug)
	else:
		form = SubscribeForm
	context = {
		'post': post,
		'form': form
	}
	return render(request, 'pages/post_detail.html', context)


def about(request):
	return render(request, 'pages/about.html', {})


def contact(request):
	return render(request, 'pages/contact_me.html', {})

app/blog/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/monokai-sublime.min.css">

	<link rel="stylesheet" href="//embed.typeform.com/css/popup.css" />
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
	<link rel="icon" type="image/png" href="{% static 'img/favicon.ico' %}" />
	<title>djangoinsights.</title>
	<script type="text/javascript">

		// Replace labnol with your disqus shortname
		var disqus_shortname = "djangoinsights";

		// Put the permalink of your web page / blog post
		var disqus_url = "http://example.com/blog{{url}}";

		// Put the permalink of your web page / blog post
		var disqus_identifier = "{{url}}";

		var disqus_loaded = false;

		// This is the function that will load Disqus comments on demand
		function disqus() {

			if (!disqus_loaded) {

				// This is to ensure that Disqus widget is loaded only once
				disqus_loaded = true;

				var e = document.createElement("script");
				e.type = "text/javascript";
				e.async = true;
				e.setAttribute('data-timestamp', +new Date());
				e.src = "//" + disqus_shortname + ".disqus.com/embed.js";
				(document.getElementsByTagName("head")[0] ||
					document.getElementsByTagName("body")[0])
					.appendChild(e);
			}
		}
	</script>
</head>

<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-success bg-gradient shadow">
		<div class="container">
			<a class="navbar-brand fst-italic" href="{% url 'blog:home' %}">Django<span
					class="logo">Insights.</span></a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
				aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link {% if request.path == '/blog/home/' %}active{% endif%}" aria-current="page"
							href="{% url 'blog:home' %}">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link {% if request.path == '/blog/tutorials/' %}active{% endif %}"
							href="{% url 'blog:all_posts' %}">Tutorials</a>
					</li>
					<li class="nav-item">
						<a class="nav-link {% if request.path == '/blog/about/' %}active{% endif %}"
							href="{% url 'blog:about' %}">About</a>
					</li>
					<li class="nav-item">
						<a class="nav-link {% if request.path == '/blog/contact/' %}active{% endif %}"
							href="{% url 'blog:contact_me' %}">Contact</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<div class="container-fluid">
		{% block header %}
		{% endblock %}
	</div>
	<main class="container">
		{% block main %}
		{% endblock %}
	</main>
	<br>
	<hr>
	<footer class="footer">
		<div class="container">
			<p class="text-center text-muted py-1">© DjangoInsights. | Django: the foundation for building outstanding
				web projects.</p>
		</div>
	</footer>

	<!-- Option 1: Bootstrap Bundle with Popper -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
		crossorigin="anonymous"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js"></script>
	<script>
		hljs.highlightAll();
	</script>
	<script src="//embed.typeform.com/next/embed.js"></script>
</body>

</html>

app/blog/templates/comments.html
<div id="disqus_thread">
    <a href="#" onclick="disqus();return false;" class="text-success">Show Comments</a>
</div>

app/blog/templates/pages/about.html
{% extends 'base.html' %}
{% load static %}


{% block main %}
<br />
<div class="text-center mt-5">
	<img class="rounded-circle headshot" src="{% static 'img/me-3.jpg' %}" alt="Headshot">
</div>
<br />
<h1>About</h1>
<p class="fs-5"><span class="bold">DjangoInsights.</span> is a project by
	<a href="https://wsvincent.com/about/">Diarra Moustapha</a>
</p>
<p class="fs-5">
	👋 Hey! I'm Diarra and welcome to my blog. My goal with this website is to transmit my knowledge about django and to
	help Django and python developers to learn more about Django and become better at it.
</p>
<p class="fs-5">
	I also offer custom Django development services for small companies and startups. You can reach me <a
		href="{% url 'blog:contact_me' %}">Here</a>
</p>

{% endblock %}

app/blog/templates/pages/all_posts.html
{% extends 'base.html' %}

{% block main %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
	<h1 class="display-4">All Tutorials</h1>
	<p class="lead">A complete list of free Django tutorials.</p>
</div>
<div class="container">
	<form class="d-flex px-5 text-center">
		<input class="form-control me-2 py-2 px-3" type="text-center" name="q" placeholder="Search" aria-label="Search">
	</form>
</div>
<div class="container p-5 text-center">
	{% for category in categories %}
	<a href="{% url 'blog:all_posts' %}?q={{ category.name }}" class="btn btn-outline-success mb-1">
		{{ category.name }}</a>
	{% endfor %}
</div>
<div class="container p-5">
	{% for post in posts %}
	<div class="tutorials">
		<h3>
			<a href="{{ post.get_absolute_url }}" class="text-success">{{ post.title }}</a>
		</h3>
		<p>{{ post.description }}</p>
	</div>
	{% endfor %}
</div>
{% endblock %}

app/blog/templates/pages/contact_me.html
{% extends 'base.html' %}


{% load static %}

{% block main %}
	<br>
	<h1>Contact</h1>
	<p class="fs-5">
		If you'd like to reach out, use the form below. Looking forward to hearing from you!
	</p>
	
	<div class="iframe" data-tf-widget="GPNwWL4E" data-tf-opacity="100" data-tf-hide-headers data-tf-iframe-props="title=My Typeform" data-tf-transitive-search-params data-tf-disable-scroll data-tf-auto-resize style="width:100%;height:500px;border: none"></div><script src="//embed.typeform.com/next/embed.js"></script>

{% endblock %}

app/blog/templates/pages/index.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% block header %}
  <div class="container-fluid">
  	<div class="px-4 py-5 mt-5 text-center">
      <h1 class="display-5 fw-bold">Django Insights</h1>
      <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">Learn the ins and outs of Django through our comprehensive guides and tutorials.</p>
        
      </div>
       <img class="d-block mx-auto" src="{% static 'img/login2.jpeg' %}" alt="" width="300" height="auto">
    </div>
    <div class="container mx-auto home-tutorial-link">
      <a class="btn btn-success" href="{% url 'blog:all_posts' %}" role="button">ALL TUTORIALS</a>
    </div>
    <br>
    <hr class="container">
  </div>
{% endblock %}

{% block main %}
  <br>
  <h2 class="subhead">Featured Articles</h2>

  {% show_recent_posts 8 %}
{% endblock %}

app/blog/templates/pages/post_detail.html
{% extends 'base.html' %}

{% block main %}
<div>
	<h1 class="post-title">{{ post.title }}</h1>
	<ul class="post-meta">
		<li>By {{ post.user.username }}</li>
		<li>
			<i class='bx bx-calendar'></i>
			<span class="text-secondary">{{ post.created }}</span>
		</li>
		<li>
			<i class='bx bxs-category-alt'></i>
			<span class="text-secondary">{{ post.category }}</span>
		</li>
	</ul>
	<div class="post-content">{{ post.content|safe }}</div>
</div>
<br>

{% if messages %}
{% for message in messages %}
<div class="alert alert-success fs-5 text-center" role="alert">
	{{ message }}
</div>
{% endfor %}
{% else %}
<div class="form">
	<h1 class="form-head">Join My Newsletter</h1>
	<p class="form-subtitle">Subscribe to get the latest tutorials/writings by email.</p>
	<form method="post" class="form-form">
		{% csrf_token %}
		{{ form.email }}
		<input type="submit" class="input subscribe bg-success" value="Subscribe">
	</form>
	<small class="form-subhead">No spam. Unsubscribe at any time.</small>
</div>
{% endif %}
<hr>
{% include 'comments.html' with url=post.slug %}
<hr>
{% endblock %}

app/blog/templates/pages/recent_posts.html
<div class="row homepage-row">
  {% for post in recent_posts %}
  <div class="col-sm-6 gy-4 d-flex aligns-items-stretch">
    <div class="card shadow">
      <div class="card-body">
        <h5 class="card-title">{{ post.title }}</h5>
        <p class="card-text">{{ post.description }}</p>
        <div class="button-center text-center">
          <a href="{{ post.get_absolute_url }}" class="btn btn-outline-success">Read now</a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>